Training:   0%|                                                                                                                                           | 0/900000 [00:00<?, ?it/s]
Epoch 1:   0%|                                                                                                                                               | 0/311 [00:00<?, ?it/s][Atorch.Size([8, 74, 256])
torch.Size([8, 137, 256])
torch.Size([8, 74, 256])
torch.Size([8, 137, 256])
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main(cfg, configs)
  File "train.py", line 89, in main
    output = model(*(batch[2:]))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dev/other/fsp/tts-king/fs_two/model/fastspeech2.py", line 92, in forward
    d_control,
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dev/other/fsp/tts-king/fs_two/model/modules.py", line 137, in forward
    x = x + pitch_embedding
RuntimeError: The size of tensor a (74) must match the size of tensor b (137) at non-singleton dimension 1

